default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= Rails.application.credentials.dig(:database, :url) %>

development:
  <<: *default
  database: <%= Rails.application.credentials.app_name %>_development

test:
  <<: *default
  database: <%= Rails.application.credentials.app_name %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= Rails.application.credentials.app_name %>_production
  cache:
    <<: *primary_production
    database: <%= Rails.application.credentials.app_name %>_production_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *primary_production
    database: <%= Rails.application.credentials.app_name %>_production_cable
    migrations_paths: db/cable_migrate
